name: Go Tests

on:
  push:
    branches: [ main, master ] # Adjust if your main branch has a different name
  pull_request:
    branches: [ main, master ] # Adjust if your main branch has a different name

jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4 # Switched to v4 for latest features/fixes

    - name: Set up Go
      uses: actions/setup-go@v5 # Switched to v5 for latest features/fixes
      with:
        go-version: '1.23' # Specify your project's Go version

    - name: Run tests
      run: go test -v ./... # -v for verbose output, ./... to run all tests
